/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package amazon.test;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

public class App {

    public static void main(String[] args) {

        var review = "Lorem ipsum dolor ut labore et dolore magna aliqua.";
        List<String> prohibitedWords = Arrays.asList("dolor", "do", "labore");

        int maxSubStringLength = calculateMaxSubStringLength(review, prohibitedWords);
        System.out.println("maxSubStringLength = " + maxSubStringLength);

    }

    private static int calculateMaxSubStringLength(String review, List<String> prohibitedWords) {
        int maxSubStringLength = 0;
        review = review.toLowerCase();
        Collections.sort(prohibitedWords, (s1, s2) -> s1.length() - s2.length());
        prohibitedWords.forEach(System.out::println);
        for (String prohibitedWord : prohibitedWords) {
            review = review.replaceAll(prohibitedWord, "|");
        }
        String[] subStrings = review.split("\\|");
        System.out.println(String.join("|", subStrings));
        maxSubStringLength = Arrays.stream(subStrings).mapToInt(String::length).max().getAsInt();
        return maxSubStringLength;
    }
}
